import Head from 'next/head'
import styles from '../styles/Home.module.css'

import { Button } from 'react-bootstrap'

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Link-Bucket | Home</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <h1>Welcome to Link-Bucket</h1>
            <p>
                This application allows you to share snippets that you can
                share.
            </p>
            <Button href='/create-snippet' variant='outline-info' size='lg'>
                Create a Snippet
            </Button>
        </div>
    )
}
